# Generated by Django 2.0.5 on 2018-06-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_haha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Haha',
        ),
    ]
